version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: btc
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"

  # backend:
  #   build:
  #     context: .
  #   container_name: backend
  #   network_mode: host
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:

